# Relational Database Configuration (MySQL via phpMyAdmin)
spring.datasource.url=jdbc:mysql://localhost:3306/bankingdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/bankingdb

# General App Properties
spring.application.name=Banking Application
server.port=8080
banking.transfer.enterprise.threshold=50000
#banking.transfer.enterprise.threshold=50000 #para pruebas oara subir a 50000 el umbral
